CREATE TABLE FACULTAD (
    id INT PRIMARY KEY IDENTITY (1, 1),
    nombre VARCHAR (50) NOT NULL
);

CREATE TABLE ESCUELA (
    id          INT PRIMARY KEY IDENTITY (1, 1),
    nombre      VARCHAR (50) NOT NULL,
	fk_facultad INT NOT NULL FOREIGN KEY REFERENCES FACULTAD(id),
);


CREATE TABLE PENSUM(
	id         INT PRIMARY KEY IDENTITY (1, 1),
	fk_escuela INT NOT NULL FOREIGN KEY REFERENCES ESCUELA(id),
);

CREATE TABLE CURSO(
	codigo   INT PRIMARY KEY,
	nombre   VARCHAR (50) NOT NULL,
	creditos INT NOT NULL
);

CREATE TABLE DETALLE_PENSUM(
	fk_pensum INT NOT NULL FOREIGN KEY REFERENCES PENSUM(id),
	fk_curso  INT NOT NULL FOREIGN KEY REFERENCES CURSO(codigo),
	PRIMARY KEY(fk_pensum,fk_curso)
);

CREATE TABLE PRERREQUISITO(
	pre      INT NOT NULL FOREIGN KEY REFERENCES CURSO(codigo),
	fk_curso INT NOT NULL FOREIGN KEY REFERENCES CURSO(codigo),
	PRIMARY KEY(pre,fk_curso)
);

CREATE TABLE ESTUDIANTE(
	carnet   INT PRIMARY KEY,
	nombre   VARCHAR (50) NOT NULL,
	passw	 VARCHAR (50) NOT NULL,
	email    VARCHAR (50) NOT NULL
);

CREATE TABLE PROGRESO (
	id            INT PRIMARY KEY IDENTITY (1, 1),
	nota          INT NOT NULL,
	valoracion    INT NOT NULL,
	comenario     VARCHAR (50) NOT NULL,
	fk_estudiante INT NOT NULL FOREIGN KEY REFERENCES ESTUDIANTE(carnet),
);


