CREATE TABLE FACULTAD (
    id INT PRIMARY KEY IDENTITY (1, 1),
    nombre VARCHAR (50) NOT NULL 
);

CREATE TABLE ESCUELA(
    id          INT PRIMARY KEY IDENTITY (1, 1),
    nombre      VARCHAR (50) NOT NULL,
	fk_facultad INT NOT NULL FOREIGN KEY REFERENCES FACULTAD(id),
);

CREATE TABLE PENSUM(
	id         INT PRIMARY KEY IDENTITY (1, 1),
	fk_escuela INT NOT NULL FOREIGN KEY REFERENCES ESCUELA(id),
);

CREATE TABLE CURSO(
	codigo      INT PRIMARY KEY,
	nombre      VARCHAR (50) NOT NULL,
	descripcion VARCHAR (50) NOT NULL,
);

CREATE TABLE DETALLE_PENSUM(
	id         INT PRIMARY KEY IDENTITY (1, 1),
	fk_pensum    INT NOT NULL FOREIGN KEY REFERENCES PENSUM(id),
	fk_curso     INT NOT NULL FOREIGN KEY REFERENCES CURSO(codigo),
	gana_credito INT NOT NULL,
	no_semestre  INT NOT NULL,
	obligatorio  BIT NOT NULL
);



CREATE TABLE PRERREQUISITO(
	fk_detalle_pensum INT NOT NULL FOREIGN KEY REFERENCES DETALLE_PENSUM(id),
	pre               INT NOT NULL FOREIGN KEY REFERENCES CURSO(codigo),
	credito           INT NOT NULL
	PRIMARY KEY(fk_detalle_pensum,pre)
);



CREATE TABLE ESTUDIANTE(
	carnet     INT PRIMARY KEY,
	nombre     VARCHAR (50) NOT NULL,
	passw	   VARCHAR (50) NOT NULL,
	email      VARCHAR (50) NOT NULL,
	fk_escuela INT NOT NULL FOREIGN KEY REFERENCES ESCUELA(id),
);

CREATE TABLE PROGRESO (
	id            INT PRIMARY KEY IDENTITY (1, 1),
	nota          INT NOT NULL,
	valoracion    INT NOT NULL,
	comenario     VARCHAR (50) NOT NULL,
	fk_estudiante INT NOT NULL FOREIGN KEY REFERENCES ESTUDIANTE(carnet),
);


DROP TABLE PROGRESO;
DROP TABLE ESTUDIANTE;
DROP TABLE PRERREQUISITO;
DROP TABLE DETALLE_PENSUM;
DROP TABLE CURSO;
DROP TABLE PENSUM;
DROP TABLE ESCUELA;
DROP TABLE FACULTAD;



