INSERT INTO FACULTAD VALUES('Ingenieria');

INSERT INTO ESCUELA VALUES('ELECTRONICA',1);
INSERT INTO ESCUELA VALUES('CIVIL',1);
INSERT INTO ESCUELA VALUES('MECANICA',1);
INSERT INTO ESCUELA VALUES('ELECTRICA',1);
INSERT INTO ESCUELA VALUES('INDUSTRIAL',1);
INSERT INTO ESCUELA VALUES('CIENCIAS Y SISTEMAS',1);
INSERT INTO ESCUELA VALUES('AMBIENTAL',1);
INSERT INTO ESCUELA VALUES('QUIMICA',1);

INSERT INTO PENSUM VALUES(6);

INSERT INTO CURSO VALUES(17,'SOCIAL HUMANISTICA',4);
INSERT INTO CURSO VALUES(101,'MATE BASICA 1',7);
INSERT INTO CURSO VALUES(3,'ORIENTACION Y LIDERAZGO',1);
INSERT INTO CURSO VALUES(69,'TECNICA COMPLEMENTARIA',3);
INSERT INTO CURSO VALUES(39,'DEPORTES 1',1);
INSERT INTO CURSO VALUES(348,'QUIMICA GENERAL 1',3);
INSERT INTO CURSO VALUES(6,'IDIOMA TECNICO 1',2);

select * from curso
UPDATE CURSO SET codigo = 8 WHERE codigo = 1


INSERT INTO CURSO VALUES(19,'SOCIAL HUMANISTICA 2',4);
INSERT INTO CURSO VALUES(103,'MATE BASICA 2',7);
INSERT INTO CURSO VALUES(5,'TECNICAS DE ESTUDIO E INVESTIGACION',3);
INSERT INTO CURSO VALUES(147,'FISICA BASICA',5);
INSERT INTO CURSO VALUES(40,'DEPORTES 2',1);
INSERT INTO CURSO VALUES(8,'IDIOMA TECNICO 2',2);

INSERT INTO CURSO VALUES(795,'LOGICA DE SISTEMAS',2);
INSERT INTO CURSO VALUES(960,'MATE DE COMPUTO',5);
INSERT INTO CURSO VALUES(770,'INTR. A LA PROG. Y COMPUTACION 1',4);
INSERT INTO CURSO VALUES(107,'MATE INTERMEDIA 1',10);
INSERT INTO CURSO VALUES(150,'FISICA 1',6);
INSERT INTO CURSO VALUES(9,'IDIOMA TECNICO 3',2);
INSERT INTO CURSO VALUES(2025,'PRACTICA INICIAL',0);

INSERT INTO CURSO VALUES(732,'ESTADISTICA',5);
INSERT INTO CURSO VALUES(796,'LENGUAJES FORMALES Y DE PROG',3);
INSERT INTO CURSO VALUES(962,'MATE DE COMPUTO 2',5);
INSERT INTO CURSO VALUES(771,'INTR. A LA PROG. Y COMPUTACION 2',5);
INSERT INTO CURSO VALUES(10,'LOGICA',2);
INSERT INTO CURSO VALUES(112,'MATE INTERMEDIA 2',5);
INSERT INTO CURSO VALUES(114,'MATE INTERMEDIA 3',5);
INSERT INTO CURSO VALUES(152,'FISICA 2',6);
INSERT INTO CURSO VALUES(11,'IDIOMA TECNICO 4',2);

INSERT INTO CURSO VALUES(736,'ANALISIS PROBABILISTICO',4);
INSERT INTO CURSO VALUES(777,'ORG. LENGUAJES Y COMPILADORES 1',4);
INSERT INTO CURSO VALUES(964,'ORGANIZACION COMPUTACIONAL',3);
INSERT INTO CURSO VALUES(772,'ESTRUCTURA DE DATOS',5);
INSERT INTO CURSO VALUES(18,'FILOSOFIA DE LA CIENCIA',3);
INSERT INTO CURSO VALUES(116,'MATE APLICADA 3',5);
INSERT INTO CURSO VALUES(118,'MATE APLICADA 1',6);
INSERT INTO CURSO VALUES(368,'PRINCIPIOS DE METROLOGIA',3);
INSERT INTO CURSO VALUES(650,'CONTABILIDAD 1',3);
INSERT INTO CURSO VALUES(28,'ECOLOGIA',3);

/* PRERREQUISITOS */
INSERT INTO PRERREQUISITO VALUES(17,19,0);
INSERT INTO PRERREQUISITO VALUES(101,103,0);
INSERT INTO PRERREQUISITO VALUES(101,147,0);
INSERT INTO PRERREQUISITO VALUES(39,40,0);
INSERT INTO PRERREQUISITO VALUES(6,8,0);


/* DETALLE PENSUM */
INSERT INTO DETALLE_PENSUM VALUES(1,4,1,1);
INSERT INTO DETALLE_PENSUM VALUES(,,,);
INSERT INTO DETALLE_PENSUM VALUES(,,,);
INSERT INTO DETALLE_PENSUM VALUES(,,,);
INSERT INTO DETALLE_PENSUM VALUES(,,,);
INSERT INTO DETALLE_PENSUM VALUES(,,,);
INSERT INTO DETALLE_PENSUM VALUES(,,,);








