INSERT INTO FACULTAD VALUES('Ingenieria');
SELECT * FROM FACULTAD;

INSERT INTO ESCUELA VALUES('ELECTRONICA',1);
INSERT INTO ESCUELA VALUES('CIVIL',1);
INSERT INTO ESCUELA VALUES('MECANICA',1);
INSERT INTO ESCUELA VALUES('ELECTRICA',1);
INSERT INTO ESCUELA VALUES('INDUSTRIAL',1);
INSERT INTO ESCUELA VALUES('CIENCIAS Y SISTEMAS',1);
INSERT INTO ESCUELA VALUES('AMBIENTAL',1);
INSERT INTO ESCUELA VALUES('QUIMICA',1);

SELECT * FROM ESCUELA;

INSERT INTO PENSUM VALUES(6);
SELECT * FROM PENSUM;

INSERT INTO CURSO VALUES(17,'SOCIAL HUMANISTICA','');
INSERT INTO CURSO VALUES(101,'MATE BASICA 1','');
INSERT INTO CURSO VALUES(3,'ORIENTACION Y LIDERAZGO','');
INSERT INTO CURSO VALUES(69,'TECNICA COMPLEMENTARIA','');
INSERT INTO CURSO VALUES(39,'DEPORTES 1','');
INSERT INTO CURSO VALUES(348,'QUIMICA GENERAL 1','');
INSERT INTO CURSO VALUES(6,'IDIOMA TECNICO 1','');



INSERT INTO CURSO VALUES(19,'SOCIAL HUMANISTICA 2','');
INSERT INTO CURSO VALUES(103,'MATE BASICA 2','');
INSERT INTO CURSO VALUES(5,'TECNICAS DE ESTUDIO E INVESTIGACION','');
INSERT INTO CURSO VALUES(147,'FISICA BASICA','');
INSERT INTO CURSO VALUES(40,'DEPORTES 2','');
INSERT INTO CURSO VALUES(8,'IDIOMA TECNICO 2','');


INSERT INTO CURSO VALUES(795,'LOGICA DE SISTEMAS','');
INSERT INTO CURSO VALUES(960,'MATE DE COMPUTO','');
INSERT INTO CURSO VALUES(770,'INTR. A LA PROG. Y COMPUTACION 1','');
INSERT INTO CURSO VALUES(107,'MATE INTERMEDIA 1','');
INSERT INTO CURSO VALUES(150,'FISICA 1','');
INSERT INTO CURSO VALUES(9,'IDIOMA TECNICO 3','');
INSERT INTO CURSO VALUES(2025,'PRACTICA INICIAL','');



INSERT INTO CURSO VALUES(732,'ESTADISTICA 1','');
INSERT INTO CURSO VALUES(796,'LENGUAJES FORMALES Y DE PROG','');
INSERT INTO CURSO VALUES(962,'MATE DE COMPUTO 2','');
INSERT INTO CURSO VALUES(771,'INTR. A LA PROG. Y COMPUTACION 2','');
INSERT INTO CURSO VALUES(10,'LOGICA','');
INSERT INTO CURSO VALUES(112,'MATE INTERMEDIA 2','');
INSERT INTO CURSO VALUES(114,'MATE INTERMEDIA 3','');
INSERT INTO CURSO VALUES(152,'FISICA 2','');
INSERT INTO CURSO VALUES(11,'IDIOMA TECNICO 4','');

SELECT * FROM CURSO;

INSERT INTO CURSO VALUES(736,'ANALISIS PROBABILISTICO','');
INSERT INTO CURSO VALUES(777,'ORG. LENGUAJES Y COMPILADORES 1','');
INSERT INTO CURSO VALUES(964,'ORGANIZACION COMPUTACIONAL','');
INSERT INTO CURSO VALUES(772,'ESTRUCTURA DE DATOS','');
INSERT INTO CURSO VALUES(18,'FILOSOFIA DE LA CIENCIA','');
INSERT INTO CURSO VALUES(116,'MATE APLICADA 3','');
INSERT INTO CURSO VALUES(118,'MATE APLICADA 1','');
INSERT INTO CURSO VALUES(368,'PRINCIPIOS DE METROLOGIA','');
INSERT INTO CURSO VALUES(650,'CONTABILIDAD 1','');
INSERT INTO CURSO VALUES(28,'ECOLOGIA','');




/* DETALLE PENSUM */
/* PENSUM,CURSO,CREDITOS,NO_SEMESTRE,OBLIGATORIO */
INSERT INTO DETALLE_PENSUM VALUES(1,17,4,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,101,7,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,3,1,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,69,3,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,39,1,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,348,3,1,1);
INSERT INTO DETALLE_PENSUM VALUES(1,6,2,1,0);


/* ****************************************************SEGUNDO SEMESTRE */
/* PENSUM,CURSO,GANA_CREDITO,NO_SEMESTRE,OBLIGATORIO */
INSERT INTO DETALLE_PENSUM VALUES(1,19,4,2,1);
INSERT INTO DETALLE_PENSUM VALUES(1,103,7,2,1);
INSERT INTO DETALLE_PENSUM VALUES(1,5,3,2,1);
INSERT INTO DETALLE_PENSUM VALUES(1,147,5,2,1);
INSERT INTO DETALLE_PENSUM VALUES(1,40,1,2,0);
INSERT INTO DETALLE_PENSUM VALUES(1,8,2,2,0);

/* PRERREQUISITOS*/
/* DETALLE_PENSUM,PRE,CREDITO_NECESARIO */
INSERT INTO PRERREQUISITO VALUES(8,17,0);
INSERT INTO PRERREQUISITO VALUES(9,101,0);
INSERT INTO PRERREQUISITO VALUES(11,101,0);
INSERT INTO PRERREQUISITO VALUES(12,39,0);
INSERT INTO PRERREQUISITO VALUES(13,6,0);

/* *********************************************************************/




/* ****************************************************TERCER SEMESTRE */
/* PENSUM,CURSO,GANA_CREDITO,NO_SEMESTRE,OBLIGATORIO */
INSERT INTO DETALLE_PENSUM VALUES(1,795,2,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,960,5,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,770,4,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,107,10,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,150,6,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,9,2,3,1);
INSERT INTO DETALLE_PENSUM VALUES(1,2025,0,3,1);

/* PRERREQUISITOS*/
/* DETALLE_PENSUM,PRE,CREDITO_NECESARIO */
INSERT INTO PRERREQUISITO VALUES(14,103,33);
INSERT INTO PRERREQUISITO VALUES(15,103,33);
INSERT INTO PRERREQUISITO VALUES(16,103,33);
INSERT INTO PRERREQUISITO VALUES(17,103,0);
INSERT INTO PRERREQUISITO VALUES(18,103,0);
INSERT INTO PRERREQUISITO VALUES(18,147,0);
INSERT INTO PRERREQUISITO VALUES(19,8,0);
INSERT INTO PRERREQUISITO VALUES(20,103,0);







/* *********************************************************************/











