//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banzapi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanzdbEntities : DbContext
    {
        public BanzdbEntities()
            : base("BanzdbEntities")
        {
        }
    
        /*protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }*/
    
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<DETALLE_PENSUM> DETALLE_PENSUM { get; set; }
        public virtual DbSet<ESCUELA> ESCUELA { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual DbSet<FACULTAD> FACULTAD { get; set; }
        public virtual DbSet<PENSUM> PENSUM { get; set; }
        public virtual DbSet<PRERREQUISITO> PRERREQUISITO { get; set; }
        public virtual DbSet<PROGRESO> PROGRESO { get; set; }
    }
}
