//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banzapi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PENSUM
    {
        public int fk_pensum { get; set; }
        public int fk_curso { get; set; }
        public int no_semestre { get; set; }
        public bool obligatorio { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual PENSUM PENSUM { get; set; }
    }
}
