//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banzapi.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRERREQUISITO
    {
        
        [Key]
        public int pre { get; set; }
        public int credito { get; set; }

        public int fk_detalle_pensum { get; set; }

        public virtual CURSO CURSO { get; set; }
        public virtual DETALLE_PENSUM DETALLE_PENSUM { get; set; }
    }
}
